(function(){
const E=RY.CmdErr,L=(n,f)=>RY.def('linux',n,f),U=RY.util,lines=U.lines;
const flags=a=>{const f=new Set(),r=[];a.forEach(x=>/^-[a-zA-Z]+$/.test(x)?[...x.slice(1)].forEach(c=>f.add(c)):r.push(x));return{f,r};};
const mode=n=>n.m||(n.t==='d'?'rwxr-xr-x':'rw-r--r--');
const text=(sh,x,c)=>{const n=sh.fs.get(sh.res(x));if(!n)throw new E(`${c}: ${x}: No such file or directory`);if(n.t==='d')throw new E(`${c}: ${x}: Is a directory`);return n.x;};
L('pwd',sh=>sh.cwd);L('whoami',()=>'user');L('hostname',()=>'ryterminal');L('date',()=>new Date().toString());
L('uname',(sh,a)=>a.includes('-a')?'Linux ryterminal 6.5.0-ry #1 SMP x86_64 GNU/Linux':'Linux');
L('clear',(sh,a,i,t)=>t.clear());
L('history',(sh,a,i,t)=>t.hist.map((h,k)=>String(k+1).padStart(4)+'  '+h).join('\n'));
L('echo',(sh,a)=>a.slice(a[0]==='-n'?1:0).join(' '));
L('ls',(sh,a)=>{const{f,r}=flags(a),res=[],sep=sh.piping?'\n':'  ';
 (r.length?r:['.']).forEach((t,_,all)=>{const n=sh.fs.get(sh.res(t));if(!n)throw new E(`ls: cannot access '${t}': No such file or directory`);
  let it=n.t==='f'?[[t,n]]:Object.keys(n.c).sort().filter(k=>f.has('a')||k[0]!=='.').map(k=>[k,n.c[k]]);
  if(f.has('a')&&n.t==='d')it=[['.',n],['..',n],...it];
  const body=f.has('l')?it.map(([k,v])=>`${v.t==='d'?'d':'-'}${mode(v)} 1 user user ${String(v.t==='f'?v.x.length:4096).padStart(5)} Oct  2 10:00 ${k}`).join('\n'):it.map(i=>i[0]).join(sep);
  res.push((all.length>1?t+':\n':'')+body);});
 return res.join('\n\n');});
L('cd',(sh,a)=>{const t=a[0]||'~',n=sh.fs.get(sh.res(t));if(!n)throw new E(`bash: cd: ${t}: No such file or directory`);if(n.t!=='d')throw new E(`bash: cd: ${t}: Not a directory`);sh.cwd=sh.res(t);});
L('mkdir',(sh,a)=>{const{f,r}=flags(a),fs=sh.fs;if(!r.length)throw new E('mkdir: missing operand');
 r.forEach(x=>{const p=sh.res(x);
  if(f.has('p')){let c='';fs.parts(p).forEach(s=>{c+='/'+s;const n=fs.get(c);if(!n){if(!fs.split(c).dir)throw new E(`mkdir: cannot create directory ‘${x}’: Not a directory`);fs.mkdir(c);}else if(n.t==='f')throw new E(`mkdir: cannot create directory ‘${x}’: Not a directory`);});return;}
  if(fs.get(p))throw new E(`mkdir: cannot create directory ‘${x}’: File exists`);
  if(!fs.split(p).dir)throw new E(`mkdir: cannot create directory ‘${x}’: No such file or directory`);fs.mkdir(p);});});
L('rmdir',(sh,a)=>{if(!a.length)throw new E('rmdir: missing operand');a.forEach(x=>{const p=sh.res(x),n=sh.fs.get(p);if(!n)throw new E(`rmdir: failed to remove '${x}': No such file or directory`);
 if(n.t!=='d')throw new E(`rmdir: failed to remove '${x}': Not a directory`);if(Object.keys(n.c).length)throw new E(`rmdir: failed to remove '${x}': Directory not empty`);sh.fs.remove(p);});});
L('touch',(sh,a)=>{if(!a.length)throw new E('touch: missing file operand');a.forEach(x=>{const p=sh.res(x);if(sh.fs.get(p))return;
 if(!sh.fs.split(p).dir)throw new E(`touch: cannot touch '${x}': No such file or directory`);sh.fs.write(p,'');});});
L('rm',(sh,a)=>{const{f,r}=flags(a);if(!r.length)throw new E('rm: missing operand');
 r.forEach(x=>{const p=sh.res(x),n=sh.fs.get(p);if(!n){if(f.has('f'))return;throw new E(`rm: cannot remove '${x}': No such file or directory`);}
  if(n.t==='d'&&!f.has('r')&&!f.has('R'))throw new E(`rm: cannot remove '${x}': Is a directory`);sh.fs.remove(p);});});
const xfer=(name,mv)=>(sh,a)=>{const{f,r}=flags(a);if(r.length<2)throw new E(`${name}: missing destination file operand after '${r[0]||''}'`);
 const dst=r.pop();r.forEach(x=>{const s=sh.res(x),n=sh.fs.get(s);if(!n)throw new E(`${name}: cannot stat '${x}': No such file or directory`);
  if(!mv&&n.t==='d'&&!f.has('r')&&!f.has('R'))throw new E(`${name}: -r not specified; omitting directory '${x}'`);
  const e=sh.fs[mv?'move':'copy'](s,sh.res(dst));
  if(e==='dst')throw new E(`${name}: cannot create regular file '${dst}': No such file or directory`);
  if(e==='same')throw new E(`${name}: '${x}' and '${dst}' are the same file`);});};
L('cp',xfer('cp',false));L('mv',xfer('mv',true));
L('cat',(sh,a,inp)=>a.length?a.map(x=>text(sh,x,'cat')).join(''):inp);
const nOpt=a=>{let n=10;const r=[];for(let i=0;i<a.length;i++){if(a[i]==='-n')n=+a[++i];else if(/^-\d+$/.test(a[i]))n=-a[i];else r.push(a[i]);}return[n,r];};
const src=(sh,r,inp,c)=>r.length?r.map(x=>text(sh,x,c)).join(''):inp;
L('head',(sh,a,i)=>{const[n,r]=nOpt(a);return lines(src(sh,r,i,'head')).slice(0,n).join('\n');});
L('tail',(sh,a,i)=>{const[n,r]=nOpt(a),v=lines(src(sh,r,i,'tail'));return n===0?'':(n<0?v.slice(Math.abs(n)):v.slice(-n)).join('\n');});
L('wc',(sh,a,inp)=>{const{f,r}=flags(a),t=r.length?text(sh,r[0],'wc'):inp,l=lines(t).length;
 return f.has('l')?String(l):`${l} ${t.split(/\s+/).filter(Boolean).length} ${t.length}`+(r[0]?' '+r[0]:'');});
L('grep',(sh,a,inp)=>{const{f,r}=flags(a),pat=r.shift();if(pat===undefined)throw new E('Usage: grep [OPTION]... PATTERNS [FILE]...');
 const fl=f.has('i')?'i':'';let re;try{re=new RegExp(pat,fl);}catch(e){re=new RegExp(pat.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),fl);}
 const files=r.length?r:[null],out=[];
 files.forEach(x=>lines(x===null?inp:text(sh,x,'grep')).forEach((l,i)=>{if(re.test(l)!==f.has('v'))out.push((files.length>1?x+':':'')+(f.has('n')?(i+1)+':':'')+l);}));
 return f.has('c')?String(out.length):out.join('\n');});
L('find',(sh,a)=>{let name=null,type=null;const r=[];for(let i=0;i<a.length;i++){if(a[i]==='-name')name=a[++i];else if(a[i]==='-type')type=a[++i];else r.push(a[i]);}
 const start=r[0]||'.',n=sh.fs.get(sh.res(start));if(!n)throw new E(`find: ‘${start}’: No such file or directory`);
 const re=name&&new RegExp('^'+name.replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*').replace(/\?/g,'.')+'$'),out=[];
 (function walk(nd,path,base){if((!re||re.test(base))&&(!type||(type==='d')===(nd.t==='d')))out.push(path);
  if(nd.t==='d')Object.keys(nd.c).sort().forEach(k=>walk(nd.c[k],path.replace(/\/$/,'')+'/'+k,k));})(n,start,start.split('/').pop());
 return out.join('\n');});
L('chmod',(sh,a)=>{if(a.length<2)throw new E('chmod: missing operand');const[m,...r]=a;
 r.forEach(x=>{const n=sh.fs.get(sh.res(x));if(!n)throw new E(`chmod: cannot access '${x}': No such file or directory`);
  if(/^[0-7]{3}$/.test(m))n.m=[...m].map(d=>[...'rwx'].map((c,i)=>d&(4>>i)?c:'-').join('')).join('');
  else{const mt=m.match(/^([ugoa]*)([+-])([rwx]+)$/);if(!mt)throw new E(`chmod: invalid mode: ‘${m}’`);const cur=[...mode(n)],who=mt[1]||'a';
   [0,1,2].forEach(g=>{if(who.includes('a')||who.includes('ugo'[g]))[...mt[3]].forEach(c=>{cur[g*3+'rwx'.indexOf(c)]=mt[2]==='+'?c:'-';});});n.m=cur.join('');}});});
})();
