(function(){window.RYNetwork=window.RYNetwork||{};const N=RYNetwork;let sequence=1;
const TYPES={pc:{label:'PC',icon:'🖥️',iface:'Ethernet0'},laptop:{label:'Laptop',icon:'💻',iface:'Ethernet0'},server:{label:'Server',icon:'🗄️',iface:'Ethernet0'},switch:{label:'Switch',icon:'🔀'},router:{label:'Router',icon:'📡'}};
function mac(){const n=(sequence++).toString(16).padStart(6,'0').slice(-6).toUpperCase();return`02:52:59:${n.slice(0,2)}:${n.slice(2,4)}:${n.slice(4)}`;}
function hostIface(name,ip,gw=''){return{id:'if0',name,mac:mac(),ip,mask:'255.255.255.0',gateway:gw,dns:'8.8.8.8',status:true,type:'ethernet'};}
N.types=TYPES;N.state={devices:[],links:[],selected:null,zoom:1,viewport:{x:0,y:0,w:1000,h:600},packetHistory:[],lastPing:null,activePacket:null,pendingLink:null};
N.createDevice=function(type,pos={x:500,y:300}){if(!TYPES[type])return null;const count=N.state.devices.filter(d=>d.type===type).length+1,hosts=N.state.devices.filter(d=>['pc','laptop','server'].includes(d.type)).length,serial=String(hosts+10).padStart(2,'0');let d={id:`${type}-${sequence++}`,type,name:`${TYPES[type].label}${count}`,x:pos.x,y:pos.y};
 if(['pc','laptop','server'].includes(type)){d.interfaces=Array.from({length:4},(_,i)=>hostIface(`Ethernet0/${i+1}`,i===0?`192.168.1.${serial}`:'',i===0?'':'')).map((i,index)=>({...i,id:`if${index}`}));if(type==='server')d.services={HTTP:true,DNS:false,DHCP:false};}
 if(type==='switch'){d.ports=Array.from({length:8},(_,i)=>({id:`p${i+1}`,name:`Ethernet0/${i+1}`,status:true,type:'ethernet'}));d.macTable={};}
 if(type==='router'){d.interfaces=Array.from({length:4},(_,i)=>({id:`g0/${i}`,name:`GigabitEthernet0/${i}`,mac:mac(),ip:i===0?'192.168.1.1':i===1?'192.168.2.1':'',mask:'255.255.255.0',status:true,type:'ethernet'}));d.routes=[];}
 N.state.devices.push(d);N.state.selected={kind:'device',id:d.id};return d;};
N.device=id=>N.state.devices.find(d=>d.id===id)||null;
N.iface=(d,id)=>d&&(d.interfaces||d.ports||[]).find(x=>x.id===id)||null;
N.ifaces=d=>d?(d.interfaces||d.ports||[]):[];
N.linkFor=(deviceId,ifaceId)=>N.state.links.find(l=>(l.a.deviceId===deviceId&&l.a.ifaceId===ifaceId)||(l.b.deviceId===deviceId&&l.b.ifaceId===ifaceId));
N.freeIface=d=>N.ifaces(d).find(i=>i.status!==false&&!N.linkFor(d.id,i.id))||null;
N.otherEnd=(link,deviceId)=>link.a.deviceId===deviceId?link.b:link.a;
N.connectPorts=function(aId,aIf,bId,bIf){const a=N.device(aId),b=N.device(bId),ia=N.iface(a,aIf),ib=N.iface(b,bIf);if(!a||!b||!ia||!ib)return{error:'No se encuentra uno de los dispositivos o puertos.'};if(aId===bId)return{error:'Un dispositivo no puede conectarse consigo mismo.'};if(aIf===bIf&&aId===bId)return{error:'No puedes conectar un puerto consigo mismo.'};if(ia.type&&ib.type&&ia.type!==ib.type)return{error:'Las interfaces no son compatibles.'};if(ia.status===false||ib.status===false)return{error:'Activa ambas interfaces antes de conectarlas.'};if(N.linkFor(aId,aIf)||N.linkFor(bId,bIf))return{error:'Uno de los puertos ya está ocupado.'};const link={id:`link-${sequence++}`,type:'ethernet',status:'connected',a:{deviceId:a.id,ifaceId:ia.id},b:{deviceId:b.id,ifaceId:ib.id}};N.state.links.push(link);return{link};};
N.connect=function(aId,bId){const a=N.device(aId),b=N.device(bId),ia=N.freeIface(a),ib=N.freeIface(b);if(!ia||!ib)return{error:`No hay interfaces o puertos libres en ${!ia?a?.name||'el dispositivo':b?.name||'el dispositivo'}.`};return N.connectPorts(aId,ia.id,bId,ib.id);};
N.duplicateDevice=function(id,pos){const src=N.device(id);if(!src)return null;const copy=JSON.parse(JSON.stringify(src));copy.id=`${copy.type}-${sequence++}`;copy.name=`${src.name} copy`;copy.x=pos?.x??src.x+40;copy.y=pos?.y??src.y+40;(copy.interfaces||[]).forEach(i=>{i.mac=mac();});if(copy.type==='switch')copy.macTable={};N.state.devices.push(copy);N.state.selected={kind:'device',id:copy.id};return copy;};
N.removeDevice=id=>{N.state.links=N.state.links.filter(l=>l.a.deviceId!==id&&l.b.deviceId!==id);N.state.devices=N.state.devices.filter(d=>d.id!==id);if(N.state.selected?.id===id)N.state.selected=null;};
N.removeLink=id=>{N.state.links=N.state.links.filter(l=>l.id!==id);if(N.state.selected?.id===id)N.state.selected=null;};
N.endpoints=()=>N.state.devices.filter(d=>['pc','laptop','server'].includes(d.type));
N.findAddress=ip=>{for(const d of N.state.devices)for(const i of d.interfaces||[])if(i.ip===ip&&i.status)return{device:d,iface:i};return null;};
N.reset=()=>{N.state.devices=[];N.state.links=[];N.state.selected=null;N.state.pendingLink=null;N.state.packetHistory=[];N.state.lastPing=null;N.state.activePacket=null;N.state.viewport={x:0,y:0,w:1000,h:600};N.state.zoom=1;sequence=1;};
N.exportData=()=>({format:'RYterminal Network Simulator',version:1,devices:N.state.devices,links:N.state.links});
N.loadData=data=>{if(!data||data.format!=='RYterminal Network Simulator'||!Array.isArray(data.devices)||!Array.isArray(data.links))throw Error('El archivo no es una topología válida de RYterminal.');const ids=new Set(),linkIds=new Set();for(const d of data.devices){if(!d||!TYPES[d.type]||typeof d.id!=='string'||!new RegExp(`^${d.type}-[a-z0-9_-]+$`).test(d.id)||ids.has(d.id)||!Number.isFinite(d.x)||!Number.isFinite(d.y)||typeof d.name!=='string')throw Error('La topología contiene un dispositivo inválido.');ids.add(d.id);if(['pc','laptop','server','router'].includes(d.type)){if(!Array.isArray(d.interfaces)||!d.interfaces.length||d.interfaces.some(i=>!i||typeof i.id!=='string'||!/^[a-z0-9/]+$/.test(i.id)||typeof i.mac!=='string'||!/^[\da-f]{2}(?::[\da-f]{2}){5}$/i.test(i.mac)))throw Error('La topología contiene una interfaz inválida.');if(d.type==='router'&&!Array.isArray(d.routes))d.routes=[];}if(d.type==='switch'){if(!Array.isArray(d.ports)||!d.ports.length||d.ports.some(i=>!i||typeof i.id!=='string'||!/^[a-z0-9]+$/.test(i.id)))throw Error('La topología contiene puertos de switch inválidos.');if(!d.macTable||typeof d.macTable!=='object')d.macTable={};}}
 const used=new Set();for(const l of data.links){if(!l||typeof l.id!=='string'||!/^link-[a-z0-9_-]+$/.test(l.id)||linkIds.has(l.id)||!ids.has(l.a?.deviceId)||!ids.has(l.b?.deviceId)||l.a.deviceId===l.b.deviceId||!N.iface(data.devices.find(d=>d.id===l.a.deviceId),l.a.ifaceId)||!N.iface(data.devices.find(d=>d.id===l.b.deviceId),l.b.ifaceId))throw Error('La topología contiene una conexión inválida.');linkIds.add(l.id);l.type=l.type||'ethernet';l.status=l.status||'connected';const ka=`${l.a.deviceId}:${l.a.ifaceId}`,kb=`${l.b.deviceId}:${l.b.ifaceId}`;if(used.has(ka)||used.has(kb))throw Error('Una interfaz aparece en más de una conexión.');used.add(ka);used.add(kb);}N.state.devices=data.devices;N.state.links=data.links;N.state.selected=null;N.state.pendingLink=null;N.state.packetHistory=[];N.state.lastPing=null;N.state.activePacket=null;const usedIds=[...data.devices,...data.links].map(x=>Number(/-(\d+)$/.exec(x.id)?.[1]||0));const macIds=data.devices.flatMap(d=>(d.interfaces||[]).map(i=>parseInt((i.mac||'').replace(/:/g,'').slice(-6),16)||0));sequence=Math.max(sequence,...usedIds,...macIds)+1;};
})();
