(function(){const N=RYNetwork,esc=RYTools.escape,svgNS='http://www.w3.org/2000/svg';
function ipLabel(d){if(d.type==='router')return(d.interfaces||[]).map(i=>i.ip||'sin IP').join(' · ');if(d.interfaces)return d.interfaces[0]?.ip||'sin IPv4';return`${d.ports.length} puertos`;}
function portPos(d,i){const n=N.ifaces(d).indexOf(i),total=N.ifaces(d).length;if(d.type==='switch')return{x:d.x+62,y:d.y-25+n*7};return{x:d.x+62,y:d.y+(n-(total-1)/2)*12};}
N.portPosition=(deviceId,ifaceId)=>{const d=N.device(deviceId),i=N.iface(d,ifaceId);return d&&i?portPos(d,i):d?{x:d.x,y:d.y}:null;};
N.renderer={draw(host){const v=N.state.viewport||{x:0,y:0,w:1000,h:600},pending=N.state.pendingLink;host.innerHTML=`<svg id="network-canvas" viewBox="${v.x} ${v.y} ${v.w} ${v.h}" role="application" aria-label="Canvas de topología de red"><defs><pattern id="net-grid" width="28" height="28" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#263656"/></pattern><filter id="net-shadow" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="0" dy="5" stdDeviation="5" flood-color="#000" flood-opacity=".35"/></filter></defs><rect class="canvas-background" x="${v.x}" y="${v.y}" width="${v.w}" height="${v.h}" fill="url(#net-grid)"/>${N.state.links.map(l=>{const a=N.device(l.a.deviceId),b=N.device(l.b.deviceId);if(!a||!b)return'';const p=N.portPosition(a.id,l.a.ifaceId),q=N.portPosition(b.id,l.b.ifaceId);return`<g class="net-link ${N.state.selected?.kind==='link'&&N.state.selected.id===l.id?'selected':''}" data-link="${l.id}" data-a="${a.id}" data-b="${b.id}"><line class="link-hit" x1="${p.x}" y1="${p.y}" x2="${q.x}" y2="${q.y}"/><line class="link-line" x1="${p.x}" y1="${p.y}" x2="${q.x}" y2="${q.y}"/><text class="link-label" x="${(p.x+q.x)/2}" y="${(p.y+q.y)/2-8}">${esc(N.iface(a,l.a.ifaceId)?.name||'')} ↔ ${esc(N.iface(b,l.b.ifaceId)?.name||'')}</text></g>`;}).join('')}${pending?(()=>{const start=pending.first?N.portPosition(pending.first.deviceId,pending.first.ifaceId):pending.origin||pending.cursor;return start&&pending.cursor?`<line class="pending-link" x1="${start.x}" y1="${start.y}" x2="${pending.cursor.x}" y2="${pending.cursor.y}"/>`:''})():''}${N.state.devices.map(d=>`<g class="net-node ${N.state.selected?.kind==='device'&&N.state.selected.id===d.id?'selected':''}" data-node="${d.id}" transform="translate(${d.x} ${d.y})" tabindex="0" role="button" aria-label="${esc(d.name)}"><rect class="node-shell" x="-62" y="-34" width="124" height="68" rx="13"/><text class="node-icon" x="0" y="-5" text-anchor="middle">${N.types[d.type].icon}</text><text class="node-name" x="0" y="14" text-anchor="middle">${esc(d.name)}</text><text class="node-meta" x="0" y="27" text-anchor="middle">${esc(ipLabel(d))}</text>${N.ifaces(d).map(i=>{const p=portPos(d,i),x=p.x-d.x,y=p.y-d.y,free=!N.linkFor(d.id,i.id),hover=N.state.hoverPort?.deviceId===d.id&&N.state.hoverPort.ifaceId===i.id;return`<circle class="net-port ${free?'free':'occupied'} ${hover?'hover':''}" data-port="${esc(i.id)}" data-device="${d.id}" cx="${x}" cy="${y}" r="5"><title>${esc(i.name)} · ${free?'libre':'conectado'}</title></circle>`}).join('')}</g>`).join('')}</svg>`;},
 updatePosition(id,x,y){const svg=document.querySelector('#network-canvas'),d=N.device(id);if(!svg||!d)return;const g=svg.querySelector(`[data-node="${id}"]`);if(g)g.setAttribute('transform',`translate(${x} ${y})`);svg.querySelectorAll(`[data-a="${id}"],[data-b="${id}"]`).forEach(gr=>{const l=N.state.links.find(x=>x.id===gr.dataset.link);if(!l)return;const p=N.portPosition(l.a.deviceId,l.a.ifaceId),q=N.portPosition(l.b.deviceId,l.b.ifaceId);gr.querySelectorAll('line').forEach(line=>{line.setAttribute('x1',p.x);line.setAttribute('y1',p.y);line.setAttribute('x2',q.x);line.setAttribute('y2',q.y);});gr.querySelector('text')?.setAttribute('x',(p.x+q.x)/2);gr.querySelector('text')?.setAttribute('y',(p.y+q.y)/2-8);});if(N.state.pendingLink?.first||N.state.pendingLink?.cursor)this.updatePending();},
 updatePending(){const svg=document.querySelector('#network-canvas'),p=N.state.pendingLink,line=svg?.querySelector('.pending-link');if(!svg||!p)return;if(!line){const n=document.createElementNS(svgNS,'line');n.setAttribute('class','pending-link');svg.append(n);return this.updatePending();}const a=p.first?N.portPosition(p.first.deviceId,p.first.ifaceId):p.origin||p.cursor,b=p.cursor;if(a&&b){line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);}},
 setViewport(){const svg=document.querySelector('#network-canvas'),v=N.state.viewport;if(svg)svg.setAttribute('viewBox',`${v.x} ${v.y} ${v.w} ${v.h}`);},
 async animate(packet){const svg=document.querySelector('#network-canvas');if(!svg||packet.path.length<2)return;const dot=document.createElementNS(svgNS,'circle');dot.setAttribute('r','8');dot.setAttribute('class',packet.type==='Echo Reply'?'packet-dot reply':'packet-dot');const title=document.createElementNS(svgNS,'title');title.textContent=`${packet.protocol} ${packet.type}`;dot.append(title);svg.append(dot);for(let i=0;i<packet.path.length-1;i++){const a=N.device(packet.path[i]),b=N.device(packet.path[i+1]);if(!a||!b)continue;await new Promise(resolve=>{const start=performance.now(),duration=420;function step(now){const t=Math.min(1,(now-start)/duration);dot.setAttribute('cx',a.x+(b.x-a.x)*t);dot.setAttribute('cy',a.y+(b.y-a.y)*t);if(t<1)requestAnimationFrame(step);else resolve();}requestAnimationFrame(step);});}dot.remove();}
};
N.zoom=factor=>{const s=Math.max(.35,Math.min(2.5,(N.state.zoom||1)*factor)),v=N.state.viewport,cx=v.x+v.w/2,cy=v.y+v.h/2,w=1000/s,h=600/s;N.state.zoom=s;N.state.viewport={x:cx-w/2,y:cy-h/2,w,h};};
N.zoomAt=(factor,x,y)=>{const old=N.state.viewport,s=Math.max(.35,Math.min(2.5,(N.state.zoom||1)*factor)),w=1000/s,h=600/s,rx=(x-old.x)/old.w,ry=(y-old.y)/old.h;N.state.zoom=s;N.state.viewport={x:x-rx*w,y:y-ry*h,w,h};};
N.fit=()=>{const ds=N.state.devices;if(!ds.length){N.state.zoom=1;N.state.viewport={x:0,y:0,w:1000,h:600};return;}const xs=ds.map(d=>d.x),ys=ds.map(d=>d.y),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2,bw=Math.max(220,Math.max(...xs)-Math.min(...xs)+200),bh=Math.max(180,Math.max(...ys)-Math.min(...ys)+160),z=Math.max(.35,Math.min(2.5,Math.min(1000/bw,600/bh)));N.state.zoom=z;const w=1000/z,h=600/z;N.state.viewport={x:cx-w/2,y:cy-h/2,w,h};};
})();
