(function(){const N=RYNetwork,IP=N.ipv4;
N.routeTable=router=>{const out=[];for(const i of router.interfaces||[]){const network=IP.cidr(i.ip,i.mask);if(i.status&&network)out.push({network,ifaceId:i.id,nextHop:'',kind:'Connected'});}for(const r of router.routes||[])if(r.network&&r.ifaceId)out.push({...r,kind:'Static'});return out;};
N.routeTo=(router,ip)=>N.routeTable(router).filter(r=>IP.inCidr(ip,r.network)).sort((a,b)=>Number(b.network.split('/')[1])-Number(a.network.split('/')[1]))[0]||null;
N.validateInterface=(device,iface)=>{const errors=[];if(!iface.status)return['Interface is down.'];if(!iface.ip)return['IPv4 address is missing.'];if(IP.parse(iface.ip)===null)return['IPv4 address is invalid.'];if(!IP.mask(iface.mask))errors.push('Subnet mask is invalid or non-contiguous.');else if(!IP.validHost(iface.ip,iface.mask))errors.push('IPv4 address is a network or broadcast address, not a host address.');if(iface.gateway){if(IP.parse(iface.gateway)===null)errors.push('Default gateway is not a valid IPv4 address.');else if(IP.network(iface.ip,iface.mask)!==null&&IP.network(iface.ip,iface.mask)!==IP.network(iface.gateway,iface.mask))errors.push('Default gateway must belong to the interface subnet.');}if(iface.dns&&IP.parse(iface.dns)===null)errors.push('DNS server must be a valid IPv4 address.');return errors;};
N.validationErrors=device=>{if(!device||!['pc','laptop','server','router'].includes(device.type))return[];return(device.interfaces||[]).filter(i=>i.ip||N.linkFor(device.id,i.id)).flatMap(i=>N.validateInterface(device,i).map(e=>`${i.name}: ${e}`));};
N.inspector=()=>{const ds=N.state.devices,ips=new Map();for(const d of ds)for(const i of d.interfaces||[])if(i.ip&&i.status){if(!ips.has(i.ip))ips.set(i.ip,[]);ips.get(i.ip).push(d.name);}const conflicts=[...ips].filter(([,a])=>a.length>1),invalid=ds.filter(d=>N.validationErrors(d).length),disconnected=ds.filter(d=>!N.state.links.some(l=>l.a.deviceId===d.id||l.b.deviceId===d.id));return{devices:ds.length,links:N.state.links.length,routers:ds.filter(d=>d.type==='router').length,switches:ds.filter(d=>d.type==='switch').length,hosts:ds.filter(d=>['pc','laptop','server'].includes(d.type)).length,conflicts,invalid,disconnected};};
 N.findPath=function(source,destination){const src=(source.interfaces||[]).find(i=>i.status&&i.ip&&N.linkFor(source.id,i.id))||(source.interfaces||[]).find(i=>i.status&&i.ip),dst=(destination.interfaces||[]).find(i=>i.status&&i.ip&&N.linkFor(destination.id,i.id))||(destination.interfaces||[]).find(i=>i.status&&i.ip);if(!src||!dst)return{error:'El origen o el destino no tiene interfaz de red configurada.'};const same=IP.sameSubnet(src.ip,dst.ip,src.mask),startLink=N.linkFor(source.id,src.id);if(!startLink)return{error:`${source.name} no está conectado a la topología.`};const first=N.otherEnd(startLink,source.id),firstDevice=N.device(first.deviceId);if(!firstDevice)return{error:'La topología tiene una conexión incompleta.'};const start={deviceId:first.deviceId,incoming:first.ifaceId,path:[source.id,first.deviceId],links:[startLink.id]};if(firstDevice.id===destination.id&&same)return{path:start.path,links:start.links};const queue=[start],seen=new Set();
 while(queue.length){const cur=queue.shift(),dev=N.device(cur.deviceId);if(!dev)continue;const key=`${dev.id}:${cur.incoming}`;if(seen.has(key))continue;seen.add(key);
  if(dev.type==='switch'){const routed=cur.path.some(id=>N.device(id)?.type==='router');for(const p of dev.ports.filter(x=>x.status&&x.id!==cur.incoming)){const l=N.linkFor(dev.id,p.id);if(!l)continue;const end=N.otherEnd(l,dev.id),next=N.device(end.deviceId);if(!next)continue;const path=cur.path.concat(next.id),links=cur.links.concat(l.id);if(next.id===destination.id&&(same||routed))return{path,links};if(next.type==='switch'||next.type==='router'&&!same)queue.push({deviceId:next.id,incoming:end.ifaceId,path,links});}}
  else if(dev.type==='router'&&!same){const incoming=N.iface(dev,cur.incoming);if(!incoming||!incoming.status)continue;const hasRouted=cur.path.slice(1,-1).some(id=>N.device(id)?.type==='router');if(!hasRouted){if(!src.gateway||src.gateway!==incoming.ip||!IP.sameSubnet(src.ip,incoming.ip,src.mask))continue;}const route=N.routeTo(dev,dst.ip);if(!route||route.ifaceId===cur.incoming)continue;const out=N.iface(dev,route.ifaceId);if(!out||!out.status)continue;const l=N.linkFor(dev.id,out.id);if(!l)continue;const end=N.otherEnd(l,dev.id),next=N.device(end.deviceId);if(!next)continue;const path=cur.path.concat(next.id),links=cur.links.concat(l.id);if(next.id===destination.id)return{path,links};if(next.type==='switch'||next.type==='router')queue.push({deviceId:next.id,incoming:end.ifaceId,path,links});}
 }
 if(same)return{error:'No hay un enlace activo entre ambos dispositivos en la misma subred.'};if(!src.gateway)return{error:'El destino está fuera de la subred local y el origen no tiene gateway configurado.'};return{error:'No hay una ruta virtual activa desde el gateway hasta el destino.'};};
})();
