/* Editor ligero para HTML/XML: textarea nativo, resaltado local y diagnósticos. */
(function(){
const T=RYTools,esc=T.escape;
const voidHtml=new Set('area base br col embed hr img input link meta param source track wbr'.split(' '));
const htmlTags='a abbr address article aside audio b blockquote body button canvas caption code colgroup data dd details dialog div dl dt em fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hr html i iframe img input label legend li link main meta nav ol option p picture pre script section select small source span strong style summary table tbody td template textarea tfoot th thead title tr ul video'.split(' ');
function highlight(text,lang){let out=esc(text);if(lang==='xml'||lang==='html'){out=out.replace(/(&lt;\/?)([\w:.-]+)/g,'$1<span class="tok-tag">$2</span>').replace(/([\w:.-]+)(=)(&quot;.*?&quot;|&#39;.*?&#39;)/g,'<span class="tok-attr">$1</span>$2<span class="tok-string">$3</span>').replace(/(&lt;!--.*?--&gt;)/gs,'<span class="tok-comment">$1</span>');}else if(lang==='js'){out=out.replace(/(&quot;.*?&quot;|&#39;.*?&#39;|`.*?`)/gs,'<span class="tok-string">$1</span>').replace(/\b(const|let|var|function|return|if|else|new|class|async|await|throw|try|catch)\b/g,'<span class="tok-keyword">$1</span>').replace(/(\/\/.*)$/gm,'<span class="tok-comment">$1</span>');}else if(lang==='css'){out=out.replace(/([.#]?[\w-]+)(\s*\{)/g,'<span class="tok-tag">$1</span>$2').replace(/([\w-]+)(\s*:)/g,'<span class="tok-attr">$1</span>$2').replace(/(&quot;.*?&quot;|&#39;.*?&#39;)/g,'<span class="tok-string">$1</span>');}return out+'\n';}
function lineCol(text,index){const before=text.slice(0,index),parts=before.split('\n');return{line:parts.length,column:parts.at(-1).length+1};}
function pairedEnter(left,right,lang){const line=left.slice(left.lastIndexOf('\n')+1),open=line.match(/<([A-Za-z][\w:.-]*)\b[^<>]*>$/),close=right.match(/^<\/([A-Za-z][\w:.-]*)\s*>/);if(!open||!close||(lang==='html'?open[1].toLowerCase()!==close[1].toLowerCase():open[1]!==close[1]))return null;const base=(line.match(/^\s*/)||[''])[0];return{text:`\n${base}    \n${base}`,cursor:base.length+5};}
function attach(ta,opt={}){const lang=opt.language||'xml',parent=ta.parentNode,controller=new AbortController(),wrap=document.createElement('div');wrap.className='ide-editor-frame';wrap.dataset.language=lang;const gutter=document.createElement('div');gutter.className='ide-gutter';gutter.setAttribute('aria-hidden','true');const surface=document.createElement('div');surface.className='ide-code-surface';const pre=document.createElement('pre');pre.className='ide-highlight';pre.setAttribute('aria-hidden','true');ta.classList.add('ide-input');parent.insertBefore(wrap,ta);wrap.append(gutter,surface);surface.append(pre,ta);let issues=[],timer=0;
 function sync(){pre.innerHTML=highlight(ta.value,lang);pre.scrollTop=ta.scrollTop;pre.scrollLeft=ta.scrollLeft;const count=Math.max(1,ta.value.split('\n').length),bad=new Map();issues.forEach(x=>bad.set(x.line,(bad.get(x.line)||0)+1));gutter.innerHTML=Array.from({length:count},(_,i)=>`<div class="ide-line-number ${bad.has(i+1)?'has-error':''}" ${bad.has(i+1)?`title="${esc(issues.filter(x=>x.line===i+1).map(x=>x.message).join('; '))}"`:''}><span>${bad.has(i+1)?'●':' '}</span>${i+1}</div>`).join('');gutter.scrollTop=ta.scrollTop;}
 function report(next=[]){issues=next;sync();const status=document.querySelector(opt.status),problems=document.querySelector(opt.problems);if(status){status.className='tool-status '+(issues.length?'error':'success');status.textContent=issues.length?`🔴 ${issues.length} ${issues.length===1?'error':'errores'}`:'✓ Válido';}const count=wrap.closest('.editor-card')?.querySelector('.ide-problems-toggle span');if(count)count.textContent=issues.length;if(problems){problems.innerHTML=issues.length?issues.map((x,i)=>`<button class="ide-problem" data-problem="${i}"><b>● Línea ${x.line}${x.column?`, columna ${x.column}`:''}</b><span>${esc(x.message)}</span></button>`).join(''):'<p class="ide-no-problems">✓ Sin problemas</p>';}}
 function validate(){if(!opt.validate)return[];const result=opt.validate(ta.value)||[];report(result);return result;}
 function changed(){sync();opt.onChange?.(ta.value);clearTimeout(timer);timer=setTimeout(validate,opt.debounce||350);}
 function replaceRange(start,end,text,select=0){ta.setRangeText(text,start,end,'select');const pos=start+select;ta.setSelectionRange(pos,pos);changed();}
 function indent(delta){const a=ta.selectionStart,b=ta.selectionEnd,val=ta.value,first=val.lastIndexOf('\n',a-1)+1,last=val.indexOf('\n',b),end=last<0?val.length:last,lines=val.slice(first,end).split('\n');const updated=lines.map(x=>delta>0?'    '+x:x.replace(/^(?: {1,4}|\t)/,'' )).join('\n');ta.setRangeText(updated,first,end,'select');ta.setSelectionRange(first,first+updated.length);changed();}
 function autoComplete(){const pos=ta.selectionStart,before=ta.value.slice(0,pos),attr=before.match(/<([\w:-]+)\s+([\w:-]*)$/),tag=before.match(/<([\w:-]*)$/);let hits=[],start=pos,attribute=false;if(attr){attribute=true;const names=lang==='html'?(attr[1].toLowerCase()==='img'?['src','alt','width','height','class','id','title']:['class','id','style','title','data-','aria-']):[...new Set([...ta.value.matchAll(/\s([\w:-]+)\s*=/g)].map(x=>x[1]))];hits=names.filter(x=>x.toLowerCase().startsWith(attr[2].toLowerCase())).slice(0,8);start=pos-attr[2].length;}else if(tag){const options=lang==='html'?htmlTags:[...new Set([...ta.value.matchAll(/<([A-Za-z_][\w:.-]*)\b/g)].map(x=>x[1]))];hits=options.filter(x=>x.toLowerCase().startsWith(tag[1].toLowerCase())).slice(0,8);start=pos-tag[1].length;}if(!hits.length)return;document.querySelector('.ide-suggestions')?.remove();const box=document.createElement('div');box.className='ide-suggestions';box.innerHTML=hits.map(x=>`<button type="button">${esc(x)}</button>`).join('');wrap.append(box);box.onclick=e=>{const v=e.target.closest('button')?.textContent;if(!v)return;const ins=attribute?`${v}=""`:v;replaceRange(start,pos,ins,attribute?ins.length-1:ins.length);box.remove();ta.focus();};setTimeout(()=>document.addEventListener('pointerdown',function close(e){if(!box.contains(e.target)){box.remove();document.removeEventListener('pointerdown',close);}}),0);}
 ta.addEventListener('input',()=>{changed();const before=ta.value.slice(0,ta.selectionStart);if(/<[-\w:]*$/.test(before)||/<[\w:-]+\s+[\w:-]*$/.test(before))autoComplete();},{signal:controller.signal});ta.addEventListener('scroll',sync,{signal:controller.signal});
 ta.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(e.key==='<')setTimeout(autoComplete,0);if(mod&&e.key==='/'){e.preventDefault();const a=ta.selectionStart,b=ta.selectionEnd,sel=ta.value.slice(a,b)||ta.value.slice(ta.value.lastIndexOf('\n',a-1)+1,ta.value.indexOf('\n',a)<0?ta.value.length:ta.value.indexOf('\n',a));const start=ta.value.indexOf(sel,a);if(lang==='html'||lang==='xml'){const commented=/^\s*<!--/.test(sel)?sel.replace(/^\s*<!--\s?|\s?-->\s*$/g,''): `<!-- ${sel} -->`;replaceRange(start,start+sel.length,commented);}else if(lang==='js'){const commented=/^\s*\/\//.test(sel)?sel.replace(/^(\s*)\/\/ ?/gm,'$1'):`// ${sel}`;replaceRange(start,start+sel.length,commented);}else if(lang==='css'){const commented=/^\s*\/\*/.test(sel)?sel.replace(/^\s*\/\*\s?|\s*\*\/\s*$/g,''):`/* ${sel} */`;replaceRange(start,start+sel.length,commented);}return;}if(mod&&e.key.toLowerCase()==='f'){e.preventDefault();findPanel(false);return;}if(mod&&e.key.toLowerCase()==='h'){e.preventDefault();findPanel(true);return;}
 if(e.key==='Tab'){e.preventDefault();if(ta.selectionStart!==ta.selectionEnd){indent(e.shiftKey?-1:1);return;}if(e.shiftKey){indent(-1);return;}replaceRange(ta.selectionStart,ta.selectionEnd,'    ',4);return;}
 if(e.key==='Enter'){const a=ta.selectionStart,b=ta.selectionEnd,left=ta.value.slice(0,a),right=ta.value.slice(b),line=left.slice(left.lastIndexOf('\n')+1),base=(line.match(/^\s*/)||[''])[0],paired=pairedEnter(left,right,lang);if(paired){e.preventDefault();replaceRange(a,b,paired.text,paired.cursor);return;}const opens=(line.match(/<([\w:.-]+)\b[^>]*>\s*$/)||[])[1],isVoid=lang==='html'&&voidHtml.has((opens||'').toLowerCase()),extra=opens&&!isVoid&&!line.endsWith('/>')?'    ':'';e.preventDefault();replaceRange(a,b,`\n${base}${extra}`,base.length+1+extra.length);return;}
 if(e.key==='>'&&ta.value[ta.selectionStart]==='>'){e.preventDefault();ta.selectionStart=ta.selectionEnd=ta.selectionStart+1;return;}if(e.key==='>'&&(lang==='xml'||lang==='html')){const left=ta.value.slice(0,ta.selectionStart),lineStart=left.lastIndexOf('\n')+1,closing=left.slice(lineStart).match(/^([ \t]*)<\/([\w:.-]+)$/);if(closing){const prior=left.slice(0,lineStart),stack=[];for(const x of prior.matchAll(/<\/?([\w:.-]+)\b[^>]*>/g)){const name=x[1].toLowerCase();if(x[0].startsWith('</')){const i=stack.lastIndexOf(name);if(i>=0)stack.splice(i,1);}else if(!x[0].endsWith('/>')&&!(lang==='html'&&voidHtml.has(name)))stack.push(name);}if(stack.at(-1)===closing[2].toLowerCase())stack.pop();const pad=' '.repeat(stack.length*4),tail=left.slice(lineStart+closing[1].length);e.preventDefault();replaceRange(lineStart,ta.selectionStart,pad+tail+'>',(pad+tail+'>').length);return;}const m=left.match(/<([A-Za-z][\w:.-]*)(?:\s[^<>]*)?$/);if(m&&!left.endsWith('/')){const tag=m[1].toLowerCase(),right=ta.value.slice(ta.selectionEnd);if(!(lang==='html'&&voidHtml.has(tag))&&!new RegExp(`^\\s*<\\/${m[1]}\\s*>`).test(right)){e.preventDefault();replaceRange(ta.selectionStart,ta.selectionEnd,`></${m[1]}>`,1);return;}}}
 if(['"',"'",'(', '[', '{'].includes(e.key)){const close={'"':'"',"'":"'",'(' :')','[':']','{':'}'}[e.key],pos=ta.selectionStart;if(ta.selectionStart!==ta.selectionEnd)return;if(ta.value[pos]===close){e.preventDefault();ta.selectionStart=ta.selectionEnd=pos+1;return;}e.preventDefault();replaceRange(pos,pos,e.key+close,1);return;}if(e.key==='>'&&ta.value[ta.selectionStart]==='>'){e.preventDefault();ta.selectionStart=ta.selectionEnd=ta.selectionStart+1;}
 },{signal:controller.signal});
 function findPanel(replace){let panel=wrap.querySelector('.ide-find');if(panel){panel.remove();return;}panel=document.createElement('div');panel.className='ide-find';panel.innerHTML=`<input placeholder="Buscar" aria-label="Buscar"><input ${replace?'':'hidden'} placeholder="Reemplazar" aria-label="Reemplazar"><button data-find="prev">↑</button><button data-find="next">↓</button>${replace?'<button data-find="one">Reemplazar</button><button data-find="all">Reemplazar todo</button>':''}<button data-find="close">×</button>`;wrap.append(panel);const inputs=panel.querySelectorAll('input'),query=inputs[0],rep=inputs[1];panel.onclick=e=>{const a=e.target.closest('[data-find]')?.dataset.find;if(a==='close'){panel.remove();ta.focus();return;}if(a==='all'&&query.value){ta.value=ta.value.split(query.value).join(rep.value);changed();return;}if(a==='one'&&ta.selectionStart!==ta.selectionEnd){replaceRange(ta.selectionStart,ta.selectionEnd,rep.value);return;}const text=ta.value,from=a==='prev'?Math.max(0,ta.selectionStart-1):ta.selectionEnd,idx=a==='prev'?text.lastIndexOf(query.value,from):text.indexOf(query.value,from);if(idx>=0){ta.focus();ta.setSelectionRange(idx,idx+query.value.length);}};query.focus();}
 const panel=ta.closest('.editor-card')?.querySelector('.ide-problems');if(panel)panel.onclick=e=>{const b=e.target.closest('[data-problem]'),issue=b&&issues[+b.dataset.problem];if(!issue)return;const lines=ta.value.split('\n'),offset=lines.slice(0,issue.line-1).reduce((n,x)=>n+x.length+1,0)+(issue.column||1)-1;ta.focus();ta.setSelectionRange(offset,Math.min(ta.value.length,offset+(issue.length||1)));};
 ta.setAttribute('autocomplete','off');ta.setAttribute('autocapitalize','off');sync();validate();return{validate,refresh:sync,report,setValue:value=>{ta.value=value;changed();validate();},destroy:()=>{controller.abort();document.querySelector('.ide-suggestions')?.remove();wrap.querySelector('.ide-find')?.remove();const container=wrap.parentNode;if(container){container.insertBefore(ta,wrap);wrap.remove();}ta.classList.remove('ide-input');},format:fn=>{const result=fn(ta.value);if(result==null)return false;ta.value=result;changed();validate();return true;},focusLine:(line,col=1)=>{const pos=lineCol(ta.value,ta.value.split('\n').slice(0,line-1).join('\n').length+(line>1?1:0)+col-1);return pos;}};
}
T.codeEditor={attach,lineCol,pairedEnter};
})();
