/* Command palette global, powered by RYTools.catalog and app navigation. */
(function(){
const T=RYTools,RECENT_KEY='ryterminal.command-palette.recent',MAX_RECENT=7;
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const actions=[
 {id:'toolbox-home',title:'Volver al inicio',description:'Regresa al centro de operaciones de RYterminal.',category:'Navegación',icon:'⌂',keywords:'home dashboard toolbox inicio volver',run:()=>T.openToolbox()},
 {id:'terminal-capture',title:'Descargar captura del terminal',description:'Guarda una captura de la salida del terminal simulado.',category:'Acciones',icon:'📸',keywords:'screenshot capture captura export terminal',run:()=>document.querySelector('#shot')?.click()}
];
const entries=()=>[...(T.catalog||[]).filter(x=>x.id==='terminal'||x.id==='library'||x.id==='challenges'||T.views?.[x.id]).map(x=>({...x,kind:'tool',run:()=>T.openCatalog(x.id)})),...actions.map(x=>({...x,kind:'action'}))];
function recent(){try{const v=JSON.parse(localStorage.getItem(RECENT_KEY)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string').slice(0,MAX_RECENT):[];}catch{return[];}}
function remember(id){try{localStorage.setItem(RECENT_KEY,JSON.stringify([id,...recent().filter(x=>x!==id)].slice(0,MAX_RECENT)));}catch{}}
let overlay=null,input=null,list=null,selected=0,results=[],returnFocus=null,closeTimer=0;
function score(item,q){if(!q)return 1;const title=normalize(item.name||item.title),desc=normalize(item.description),cat=normalize(item.category),kw=normalize(`${item.keywords||''} ${item.shortcut||''}`);if(title===q)return 100;if(title.startsWith(q))return 80;if(title.includes(q))return 65;if(kw.includes(q))return 48;if(desc.includes(q))return 32;if(cat.includes(q))return 20;const words=q.split(/\s+/).filter(Boolean);if(words.every(w=>`${title} ${desc} ${cat} ${kw}`.includes(w)))return 10;return 0;}
function itemMarkup(x,i){const title=x.name||x.title,cat=x.category||'Herramientas',category=({Systems:'Sistemas',Network:'Redes',Development:'Desarrollo',Calculators:'Utilidades',Learning:'Aprendizaje',Navigation:'Navegación',Actions:'Acciones'})[cat]||cat;return`<button id="command-option-${i}" class="command-item ${i===selected?'active':''}" role="option" aria-selected="${i===selected}" data-index="${i}"><span class="command-icon" aria-hidden="true">${x.icon||'⌘'}</span><span class="command-copy"><b>${T.escape(title)}</b><small>${T.escape(x.description||'')}</small></span><span class="command-category">${T.escape(category)}</span></button>`;}
function render(){const q=normalize(input.value),all=entries();let groups=[];if(!q){const ids=recent(),r=ids.map(id=>all.find(x=>x.id===id)).filter(Boolean);const seen=new Set(r.map(x=>x.id));if(r.length)groups.push({label:'RECIENTES',items:r});const rest=all.filter(x=>!seen.has(x.id));if(rest.length)groups.push({label:'HERRAMIENTAS Y ACCIONES',items:rest});}else{const ranked=all.map(x=>({x,s:score(x,q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s||(a.x.name||a.x.title).localeCompare(b.x.name||b.x.title));if(ranked.length)groups.push({label:'RESULTADOS',items:ranked.map(x=>x.x)});}
 results=groups.flatMap(g=>g.items);input?.removeAttribute('aria-activedescendant');if(!results.length){list.innerHTML='<div class="command-empty"><b>No se encontraron resultados</b><span>Busca una herramienta, categoría o acción.</span></div>';return;}
 let ix=0;list.innerHTML=groups.map(g=>`<section class="command-group"><div class="command-group-title">${g.label}</div>${g.items.map(x=>itemMarkup(x,ix++)).join('')}</section>`).join('');if(results.length)input?.setAttribute('aria-activedescendant','command-option-0');
}
function close(){if(!overlay)return;clearTimeout(closeTimer);const old=overlay,focus=returnFocus;overlay=null;input=null;list=null;old.classList.add('closing');closeTimer=setTimeout(()=>old.remove(),130);if(focus?.isConnected)focus.focus();}
function open(){if(overlay){close();return;}returnFocus=document.activeElement;overlay=document.createElement('div');overlay.className='command-overlay';overlay.innerHTML=`<section class="command-palette" role="dialog" aria-modal="true" aria-label="Paleta de comandos de RYterminal"><div class="command-search"><span aria-hidden="true">⌕</span><input type="search" autocomplete="off" spellcheck="false" placeholder="Buscar herramientas y acciones..." aria-label="Buscar herramientas y acciones" aria-autocomplete="list" aria-controls="command-results"><kbd>ESC</kbd></div><div id="command-results" class="command-results" role="listbox" aria-label="Resultados de comandos"></div><footer class="command-hints"><span><kbd>↑</kbd><kbd>↓</kbd> Navegar</span><span><kbd>↵</kbd> Abrir</span><span><kbd>Esc</kbd> Cerrar</span><span class="command-shortcut">${/Mac|iPhone|iPad/.test(navigator.platform||'')?'⌘ K':'Ctrl K'}</span></footer></section>`;document.body.append(overlay);input=overlay.querySelector('input');list=overlay.querySelector('.command-results');selected=0;render();input.oninput=()=>{selected=0;render();};overlay.addEventListener('click',e=>{if(e.target===overlay)close();});overlay.querySelector('.command-palette').addEventListener('click',e=>e.stopPropagation());list.onclick=e=>{const b=e.target.closest('[data-index]');if(b)activate(+b.dataset.index);};list.onmousemove=e=>{const b=e.target.closest('[data-index]');if(!b)return;selected=+b.dataset.index;refreshActive();};requestAnimationFrame(()=>input?.focus());}
function refreshActive(){if(results.length)input?.setAttribute('aria-activedescendant',`command-option-${selected}`);list?.querySelectorAll('[data-index]').forEach(b=>{const on=+b.dataset.index===selected;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});list?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'});}
function activate(i){const cmd=results[i];if(!cmd)return;close();if(cmd.kind==='tool')remember(cmd.id);cmd.run();}
function onKey(e){if(!overlay)return;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}else if(e.key==='ArrowDown'){e.preventDefault();selected=Math.min(selected+1,results.length-1);refreshActive();}else if(e.key==='ArrowUp'){e.preventDefault();selected=Math.max(0,selected-1);refreshActive();}else if(e.key==='Enter'){e.preventDefault();activate(selected);}}
function globalKey(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopPropagation();overlay?close():open();return;}if(overlay)onKey(e);}
document.querySelector('#command-open')?.addEventListener('click',open);document.addEventListener('keydown',globalKey,true);const shortcut=/Mac|iPhone|iPad/.test(navigator.platform||'')?'⌘ K':'Ctrl K';document.querySelector('#command-open kbd').textContent=shortcut;
})();
