/* Home Command Center: nodes and labels derive from the shared tool catalog. */
(function(){
const T=RYTools,labels={Systems:'Sistemas',Network:'Redes',Development:'Desarrollo',Calculators:'Utilidades',Learning:'Aprendizaje'};
const points=[[50,11],[75,19],[88,39],[84,70],[62,88],[34,88],[12,67],[12,35],[34,17]];
function tools(){return(T.catalog||[]).filter(x=>(x.id==='terminal'||!!T.views?.[x.id])&&x.category!=='Learning');}
function age(at){const m=Math.max(0,Math.floor((Date.now()-at)/60000));return m===0?'ahora':m===1?'hace 1 min':`hace ${m} min`;}
function activityMarkup(){const list=T.getActivity();return list.length?list.map(x=>`<div class="cc-activity-row"><i></i><span>${T.escape(x.text)}</span><time>${age(x.at)}</time></div>`).join(''):'<div class="cc-activity-empty">Aún no hay actividad. Abre una herramienta para empezar.</div>';}
function render(host){const all=tools(),categories=[...new Set(all.map(x=>x.category))],coords=new Map(all.map((x,i)=>[x.id,points[i%points.length]]));const wires=all.map(x=>{const [px,py]=coords.get(x.id),cx=500,cy=350;return`<g class="cc-wire-group" data-wire="${x.category}"><line x1="${cx}" y1="${cy}" x2="${px*10}" y2="${py*7}"/><circle r="2.2"><animateMotion dur="${5+(px%3)}s" repeatCount="indefinite" path="M ${cx} ${cy} L ${px*10} ${py*7}"/></circle></g>`;}).join('');
 const nodes=all.map(x=>{const [px,py]=coords.get(x.id);return`<button class="cc-tool-node" data-open="${x.id}" data-category="${x.category}" style="--nx:${px}%;--ny:${py}%" aria-label="Abrir ${T.escape(x.name)}"><span class="cc-node-icon">${x.icon}</span><span class="cc-node-name">${T.escape(x.name)}</span><small>${T.escape(labels[x.category]||x.category)}</small><span class="cc-node-description">${T.escape(x.description)}</span></button>`;}).join('');
 const count=all.length,sim=!!(window.RYNetwork&&typeof RYNetwork.ping==='function');host.innerHTML=`<div class="cc-shell"><nav class="cc-rail" aria-label="Navegación del entorno"><button class="on" data-filter-category="all">⌂ <span>Inicio</span></button>${categories.map(c=>`<button data-filter-category="${c}">${({Systems:'▣',Network:'⌁',Development:'‹›',Calculators:'⊞',Learning:'◷'})[c]||'·'} <span>${labels[c]||c}</span></button>`).join('')}<button class="cc-rail-palette" data-palette>⌘ <span>Buscar</span></button></nav>
 <div class="cc-topline"><div><span class="tag">RYterminal · CENTRO DE OPERACIONES</span><h1>Entorno de trabajo</h1></div><div class="cc-live"><i></i>LISTO PARA TRABAJAR</div></div>
 <div class="cc-layout"><aside class="cc-side cc-left"><button class="cc-window cc-terminal-preview" data-open="terminal"><span class="cc-window-head"><b>TERMINAL</b><small><i></i> ACTIVA</small></span><pre><span>$ ipconfig</span>
IPv4: 192.168.1.24
Máscara: 255.255.255.0
Puerta de enlace: 192.168.1.1

$ ping 192.168.1.1
Respuesta desde 192.168.1.1</pre><span class="cc-window-link">Abrir terminal →</span></button><button class="cc-window cc-network-preview" data-open="network"><span class="cc-window-head"><b>SIMULADOR DE REDES</b><small>${sim?'MOTOR ACTIVO':'DISPONIBLE'}</small></span><svg viewBox="0 0 240 120" aria-label="Vista previa de topología virtual"><g class="cc-topology-lines"><path d="M120 25V57M120 57L50 95M120 57L190 95"/></g><g class="cc-topology-nodes"><rect x="96" y="9" width="48" height="26" rx="7"/><rect x="88" y="47" width="64" height="25" rx="7"/><rect x="26" y="87" width="48" height="24" rx="7"/><rect x="166" y="87" width="48" height="24" rx="7"/><text x="120" y="27">PC</text><text x="120" y="64">SWITCH</text><text x="50" y="103">PC</text><text x="190" y="103">SERVIDOR</text></g></svg><span class="cc-window-link">Topología de ejemplo · 4 nodos →</span></button></aside>
 <section class="cc-core"><div class="cc-core-title"><span>CONSTELACIÓN DE HERRAMIENTAS</span><span>Selecciona un nodo para abrirlo</span></div><div class="cc-category-strip"><button class="on" data-filter-category="all">Todas</button>${categories.map(c=>`<button data-filter-category="${c}">${labels[c]||c}</button>`).join('')}</div><div class="cc-constellation"><svg class="cc-wires" viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><defs><filter id="cc-soft-glow"><feGaussianBlur stdDeviation="2" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>${wires}</svg><div class="cc-hub"><span>RY</span><b>RYterminal</b><small>ENTORNO LOCAL</small></div>${nodes}</div></section>
 <aside class="cc-side cc-right"><button class="cc-window cc-code-preview" data-open="xml"><span class="cc-window-head"><b>XML STUDIO</b><small>✓ XML VÁLIDO</small></span><pre><span class="cc-syntax-tag">&lt;servidores&gt;</span>
    <span class="cc-syntax-tag">&lt;servidor</span> id="01"&gt;
        <span class="cc-syntax-tag">&lt;nombre&gt;</span>web01<span class="cc-syntax-tag">&lt;/nombre&gt;</span>
    <span class="cc-syntax-tag">&lt;/servidor&gt;</span>
<span class="cc-syntax-tag">&lt;/servidores&gt;</span></pre><span class="cc-window-link">Abrir XML Studio →</span></button><button class="cc-window cc-code-preview" data-open="json"><span class="cc-window-head"><b>JSON STUDIO</b><small>✓ JSON VÁLIDO</small></span><pre>{
  <span class="cc-syntax-key">"servidor"</span>: <span class="cc-syntax-string">"web01"</span>,
  <span class="cc-syntax-key">"ip"</span>: <span class="cc-syntax-string">"192.168.1.10"</span>,
  <span class="cc-syntax-key">"activo"</span>: <span class="cc-syntax-bool">true</span>
}</pre><span class="cc-window-link">Abrir JSON Studio →</span></button><section class="cc-environment"><div class="cc-window-head"><b>ENTORNO</b><small>MODO LOCAL</small></div><div><span>Motor de simulación</span><b><i></i>${sim?'ACTIVO':'DISPONIBLE'}</b></div><div><span>Herramientas</span><b>${count} DISPONIBLES</b></div><div><span>Datos</span><b>LOCALES</b></div></section></aside></div>
 <section class="cc-activity"><div class="cc-activity-head"><div><span>SESIÓN LOCAL</span><b>Actividad reciente</b></div><small>Se guarda en este navegador</small></div><div class="cc-activity-list">${activityMarkup()}</div></section><footer class="cc-footer"><span>RYterminal · entorno informático local</span><span>Sin conexión a servicios externos</span></footer></div>`;
 host.onclick=e=>{const open=e.target.closest('[data-open]')?.dataset.open;if(open){T.openCatalog?.(open);return;}if(e.target.closest('[data-palette]')){document.querySelector('#command-open')?.click();return;}const f=e.target.closest('[data-filter-category]');if(f){const category=f.dataset.filterCategory;host.querySelectorAll('[data-filter-category]').forEach(b=>b.classList.toggle('on',b.dataset.filterCategory===category));host.querySelectorAll('.cc-tool-node').forEach(n=>n.classList.toggle('dimmed',category!=='all'&&n.dataset.category!==category));host.querySelectorAll('.cc-wire-group').forEach(n=>n.classList.toggle('dimmed',category!=='all'&&n.dataset.wire!==category));host.querySelectorAll('.cc-window[data-category]').forEach(n=>n.classList.toggle('dimmed',category!=='all'&&n.dataset.category!==category));}};
 const update=()=>{const list=host.querySelector('.cc-activity-list');if(list)list.innerHTML=activityMarkup();};window.addEventListener('ryterminal:activity',update);}
T.renderCommandCenter=render;
})();
