(function(){
const T=RYTools,bases={10:'Decimal',2:'Binario',8:'Octal',16:'Hexadecimal'},digits='0123456789ABCDEF';
function render(host){host.innerHTML=`<section class="tool-head"><div><span class="tag">CONVERSIÓN GUIADA</span><h2>Calculadora de sistemas numéricos</h2><p>Convierte enteros entre decimal, binario, octal y hexadecimal. Admite números grandes.</p></div></section><div class="number-layout"><section class="tool-card"><label>Base de entrada<select id="num-base">${Object.entries(bases).map(([n,v])=>`<option value="${n}">${v} (base ${n})</option>`).join('')}</select></label><label>Número<input id="num-input" value="42" spellcheck="false" autocomplete="off" placeholder="Ej. 42, 101010, FF"></label><div id="num-status" class="tool-status info">Introduce un entero positivo o cero.</div><div class="result-grid" id="num-results"></div><div class="crow"><button class="pri" id="num-copy">Copiar resultados</button><button id="num-clear">Limpiar</button></div></section><section class="tool-card"><h3>¿Cómo se obtiene?</h3><div id="num-steps" class="steps"></div><p class="mut">Para pasar a otra base, dividimos repetidamente entre la base destino y leemos los restos desde abajo.</p></section></div>`;
const input=host.querySelector('#num-input'),base=host.querySelector('#num-base'),status=host.querySelector('#num-status');
function val(){let raw=input.value.trim().replace(/\s+/g,'').toUpperCase(),b=Number(base.value);if(!raw)return null;let re=b===16?/^[0-9A-F]+$/:new RegExp(`^[0-${b-1}]+$`);if(!re.test(raw))throw Error(`«${raw}» no es válido en base ${b}. ${b===16?'Usa 0–9 y A–F.':`Usa dígitos de 0 a ${b-1}.`}`);let n=0n;for(const c of raw)n=n*BigInt(b)+BigInt(digits.indexOf(c));return n;}
function fmt(n,b){return n.toString(b).toUpperCase();}
function convert(){try{const n=val();if(n===null){host.querySelector('#num-results').innerHTML='';host.querySelector('#num-steps').innerHTML='<p class="mut">Los pasos aparecerán al escribir un número.</p>';T.setStatus(status,'Introduce un entero positivo o cero.','info');return;}const results=Object.entries(bases).map(([b,label])=>[label,fmt(n,Number(b))]);host.querySelector('#num-results').innerHTML=results.map(([k,v])=>`<div class="num-result"><small>${k}</small><strong>${v}</strong></div>`).join('');
let lines=[];if(Number(base.value)!==10){let parts=[...input.value.trim().toUpperCase()].map(c=>digits.indexOf(c));lines.push(`<p><b>${T.escape(input.value.trim().toUpperCase())} en base ${base.value} a decimal:</b></p><code>${parts.map((d,i)=>`${d} × ${base.value}<sup>${parts.length-i-1}</sup>`).join(' + ')} = ${n}</code>`);}const targets=[2,8,16].map(b=>{let q=n,rows=[];if(q===0n)rows.push(`0 ÷ ${b} = 0 resto 0`);while(q>0n){const rem=q%BigInt(b),next=q/BigInt(b);rows.push(`${q} ÷ ${b} = ${next} resto ${rem.toString().toUpperCase()}`);q=next;}return `<div class="step-block"><b>${n} → base ${b} (${bases[b]})</b><pre>${rows.join('\n')}</pre><span class="mut">Lee los restos de abajo hacia arriba: <strong>${fmt(n,b)}</strong></span></div>`;});host.querySelector('#num-steps').innerHTML=(lines.length?lines.join(''):'<p class="mut">El valor ya está en decimal; ahora generamos las demás bases.</p>')+targets.join('');T.setStatus(status,'Número válido · conversión actualizada.','success');}catch(e){host.querySelector('#num-results').innerHTML='';host.querySelector('#num-steps').innerHTML='<p class="mut">Corrige el valor para ver el procedimiento.</p>';T.setStatus(status,e.message,'error');}}
input.oninput=convert;base.onchange=convert;host.querySelector('#num-clear').onclick=()=>{input.value='';convert();input.focus();};host.querySelector('#num-copy').onclick=e=>{const n=val();if(n!==null){T.copy(Object.entries(bases).map(([b,k])=>`${k}: ${fmt(n,+b)}`).join('\n'),e.currentTarget);T.recordActivity?.('numbers','Conversión de sistemas numéricos copiada');}};convert();}
RYTools.views=RYTools.views||{};RYTools.views.numbers=render;
})();
