(function(){const T=RYTools;const groups={
Data:[['bit','bit',1],['byte','byte',8],['KB','KB (1000 byte)',8e3],['MB','MB (1000 byte)',8e6],['GB','GB (1000 byte)',8e9],['TB','TB (1000 byte)',8e12],['PB','PB (1000 byte)',8e15],['KiB','KiB (1024 byte)',8192],['MiB','MiB (1024 byte)',8192*1024],['GiB','GiB (1024 byte)',8192*1024**2],['TiB','TiB (1024 byte)',8192*1024**3],['PiB','PiB (1024 byte)',8192*1024**4]],
Network:[['bit/s','bit/s',1],['Kbit/s','Kbit/s',1e3],['Mbit/s','Mbit/s',1e6],['Gbit/s','Gbit/s',1e9],['Tbit/s','Tbit/s',1e12],['B/s','B/s',8],['KB/s','KB/s',8e3],['MB/s','MB/s',8e6],['GB/s','GB/s',8e9]],
Frequency:[['Hz','Hz',1],['kHz','kHz',1e3],['MHz','MHz',1e6],['GHz','GHz',1e9]],
Time:[['ns','ns',1e-9],['µs','µs',1e-6],['ms','ms',1e-3],['s','s',1],['min','min',60],['h','h',3600]]};
function render(host){host.innerHTML=`<section class="tool-head"><div><span class="tag">INFORMATION TECHNOLOGY</span><h2>IT Unit Converter</h2><p>Convierte unidades de datos, velocidades de red, frecuencia y tiempo.</p></div></section><section class="tool-card"><div class="unit-controls"><label>Categoría<select id="unit-category">${Object.keys(groups).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Valor<input id="unit-value" type="number" step="any" value="100"></label><label>Desde<select id="unit-from"></select></label><button id="unit-swap" title="Intercambiar unidades">⇄</button><label>Hacia<select id="unit-to"></select></label></div><div class="crow"><button class="pri" id="unit-convert">Convertir</button><button id="unit-copy">Copiar</button><button id="unit-clear">Limpiar</button></div><div id="unit-status" class="tool-status info"></div><div id="unit-result" class="storage-result"></div><div id="unit-explanation" class="step-block"></div><p id="unit-note" class="mut"></p></section>`;
const cat=host.querySelector('#unit-category'),value=host.querySelector('#unit-value'),from=host.querySelector('#unit-from'),to=host.querySelector('#unit-to'),status=host.querySelector('#unit-status');const fmt=n=>Number(n.toPrecision(10)).toLocaleString('es-ES',{maximumFractionDigits:10});
function options(){const list=groups[cat.value];from.innerHTML=list.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');to.innerHTML=list.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');if(cat.value==='Network'){from.value='Mbit/s';to.value='MB/s';}else if(cat.value==='Frequency'){from.value='GHz';to.value='MHz';}else if(cat.value==='Time'){from.value='ms';to.value='s';}else{from.value='GB';to.value='MB';}convert();}
function convert(){const n=Number(value.value),a=groups[cat.value].find(x=>x[0]===from.value),b=groups[cat.value].find(x=>x[0]===to.value);if(value.value===''||!Number.isFinite(n)){T.setStatus(status,'Introduce un número válido.','error');host.querySelector('#unit-result').textContent='';host.querySelector('#unit-explanation').textContent='';return;}const out=n*a[2]/b[2];host.querySelector('#unit-result').innerHTML=`<small>Resultado</small><strong>${fmt(out)} ${b[0]}</strong>`;let explanation;if(cat.value==='Network'&&a[0].includes('bit')&&b[0].includes('B/'))explanation=`${fmt(n)} ÷ 8 = ${fmt(out)} ${b[0]} · 8 bits = 1 byte`;else explanation=`${fmt(n)} ${a[0]} × ${fmt(a[2])} ${cat.value==='Network'?'bit/s':cat.value==='Frequency'?'Hz':cat.value==='Time'?'s':'bit'} / ${fmt(b[2])} ${cat.value==='Network'?'bit/s':cat.value==='Frequency'?'Hz':cat.value==='Time'?'s':'bit'} = ${fmt(out)} ${b[0]}`;host.querySelector('#unit-explanation').textContent=explanation;host.querySelector('#unit-note').textContent=cat.value==='Data'?'KB, MB, GB, TB y PB usan múltiplos decimales; KiB, MiB, GiB, TiB y PiB usan múltiplos binarios.':cat.value==='Network'?'Las velocidades en bit/s se dividen entre 8 para expresarse en byte/s.':'';T.setStatus(status,'Conversión actualizada.','success');return{out,unit:b[0]};}
cat.onchange=options;from.onchange=convert;to.onchange=convert;value.oninput=convert;host.querySelector('#unit-convert').onclick=convert;host.querySelector('#unit-swap').onclick=()=>{const x=from.value;from.value=to.value;to.value=x;convert();};host.querySelector('#unit-copy').onclick=e=>{const r=convert();if(r)T.copy(`${fmt(r.out)} ${r.unit}`,e.currentTarget);};host.querySelector('#unit-clear').onclick=()=>{value.value='';convert();value.focus();};options();}
RYTools.views=RYTools.views||{};RYTools.views.units=render;})();
