(function(){
const T=RYTools,S=T.toolState,esc=T.escape;
function inspectXml(source){const errors=[],stack=[],scan=source.replace(/<!--[\s\S]*?-->|<!\[CDATA\[[\s\S]*?\]\]>|<\?[\s\S]*?\?>|<!DOCTYPE[^>]*>/gi,x=>x.replace(/[^\n]/g,' ')),tag=/<\/?([A-Za-z_][\w:.-]*)(?:\s[^<>]*?)?\s*(\/?)>/g;let m,roots=0;
 while((m=tag.exec(scan))){const token=m[0],name=m[1],closing=token.startsWith('</'),at=m.index,before=source.slice(0,at),line=before.split('\n').length,column=at-(before.lastIndexOf('\n')+1)+1;
 if(token.startsWith('<!--')||token.startsWith('<![CDATA[')||token.startsWith('<?')||token.startsWith('<!'))continue;
 if(closing){const expected=stack.at(-1);if(!expected){errors.push({line,column,length:token.length,message:`Unexpected closing tag </${name}>.`});}else if(expected.name!==name){errors.push({line,column,length:token.length,message:`Expected </${expected.name}>, found </${name}>.`});}else stack.pop();}
 else{if(!stack.length)roots++;if(!m[2])stack.push({name,index:at});}
 }
 if(!errors.length&&stack.length){const x=stack.at(-1),before=source.slice(0,x.index);errors.push({line:before.split('\n').length,column:x.index-(before.lastIndexOf('\n')+1)+1,length:1,message:`Unclosed tag <${x.name}>. Expected </${x.name}>.`});}
 if(!errors.length){const doc=new DOMParser().parseFromString(source,'application/xml'),pe=doc.querySelector('parsererror');if(pe){const msg=pe.textContent.replace(/\s+/g,' ').trim(),loc=msg.match(/line\s*(\d+)[^\d]+column\s*(\d+)/i)||msg.match(/line\s*(\d+)/i);errors.push({line:+(loc?.[1]||1),column:+(loc?.[2]||1),length:1,message:msg.slice(0,200)});}else if(roots!==1)errors.push({line:1,column:1,length:1,message:roots===0?'XML must contain one root element.':'XML cannot contain multiple root elements.'});}
 return errors;
}
function formatXml(source){const doc=new DOMParser().parseFromString(source,'application/xml');if(doc.querySelector('parsererror'))return null;function node(n,depth=0){const pad=' '.repeat(depth*4);if(n.nodeType===8)return`${pad}<!--${n.data}-->`;if(n.nodeType===3)return n.data.trim()?pad+n.data.trim().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'):'';if(n.nodeType!==1)return'';const attrs=[...n.attributes].map(a=>` ${a.name}="${a.value.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"`).join(''),open=`${pad}<${n.tagName}${attrs}>`,children=[...n.childNodes].map(c=>node(c,depth+1)).filter(Boolean);if(!children.length)return`${pad}<${n.tagName}${attrs}/>`;if(children.length===1&&children[0].trim()[0]!=='<')return`${open}${children[0].trim()}</${n.tagName}>`;return`${open}\n${children.join('\n')}\n${pad}</${n.tagName}>`;}return`<?xml version="1.0" encoding="UTF-8"?>\n${node(doc.documentElement)}`;}
function render(host){host.innerHTML=`<section class="tool-head"><div><span class="tag">DOCUMENTOS XML · LOCAL</span><h2>XML Studio</h2><p>Valida, ordena y explora documentos XML en tu navegador.</p></div><div class="crow"><button id="xml-validate" class="pri">Validar</button><button id="xml-format">Formatear</button><button id="xml-mini">Minificar</button><button id="xml-example">Ejemplo</button><button id="xml-import">Importar</button><button id="xml-copy">Copiar</button><button id="xml-download">Descargar</button><button id="xml-clear">Limpiar</button></div></section><div class="studio-layout"><section class="editor-card"><div class="editor-top"><b>Editor XML</b><span id="xml-state" class="ide-state">✓ Válido</span></div><textarea id="xml-code" class="code-editor" spellcheck="false" aria-label="Editor XML"></textarea><section class="ide-problems-wrap"><button class="ide-problems-toggle" type="button">Problemas <span id="xml-problem-count">0</span><b>⌄</b></button><div class="ide-problems"></div></section><div class="editor-foot">Tab indentar · Ctrl+/ comentar · Ctrl+F buscar · cierre automático</div></section><section class="tree-card"><div class="editor-top"><b>Estructura</b><input id="xml-search" placeholder="Buscar etiqueta…"></div><div id="xml-tree" class="tree-view"><p class="mut">El árbol aparecerá cuando el XML sea válido.</p></div></section></div>`;
const ta=host.querySelector('#xml-code'),tree=host.querySelector('#xml-tree'),panel=host.querySelector('.ide-problems'),saved=(()=>{try{return localStorage.getItem('ryterminal.xml')}catch{return null}})();ta.value=saved??S.xml;
function validate(code){const issues=inspectXml(code);host.querySelector('#xml-problem-count').textContent=issues.length;if(issues.length){tree.innerHTML='<p class="mut">Corrige el error indicado para mostrar el árbol.</p>';return issues;}drawTree();return issues;}
function drawTree(){const doc=new DOMParser().parseFromString(ta.value,'application/xml'),query=host.querySelector('#xml-search').value.toLowerCase();function item(n,depth=0){if(depth>24)return'';const attrs=[...n.attributes].map(a=>`${a.name}="${a.value}"`).join(' '),kids=[...n.children].map(x=>item(x,depth+1)).join(''),text=[...n.childNodes].filter(x=>x.nodeType===3&&x.textContent.trim()).map(x=>`<span class="tree-value">${esc(x.textContent.trim())}</span>`).join(''),match=!query||n.tagName.toLowerCase().includes(query)||attrs.toLowerCase().includes(query)||n.textContent.toLowerCase().includes(query);if(!match)return'';return`<details open class="xml-node"><summary>&lt;${esc(n.tagName)}${attrs?' '+esc(attrs):''}&gt;</summary>${text}${kids}</details>`;}tree.innerHTML=item(doc.documentElement)||'<p class="mut">Sin coincidencias.</p>';}
const editor=T.codeEditor.attach(ta,{language:'xml',status:'#xml-state',problems:'.ide-problems',debounce:300,validate,onChange:v=>{S.xml=v;try{localStorage.setItem('ryterminal.xml',v)}catch{}}});
host.querySelector('#xml-validate').onclick=()=>{const issues=editor.validate();if(!issues?.length)T.recordActivity?.('xml','XML validado correctamente');};host.querySelector('#xml-search').oninput=()=>{editor.validate();};host.querySelector('.ide-problems-toggle').onclick=()=>host.querySelector('.ide-problems-wrap').classList.toggle('collapsed');host.querySelector('#xml-format').onclick=()=>{if(!editor.format(formatXml))T.setStatus(host.querySelector('#xml-state'),'No se puede formatear XML incorrecto. Corrige los errores primero.','error');};host.querySelector('#xml-mini').onclick=()=>{const d=new DOMParser().parseFromString(ta.value,'application/xml');if(d.querySelector('parsererror'))return editor.validate();editor.setValue(new XMLSerializer().serializeToString(d));};host.querySelector('#xml-example').onclick=()=>{editor.setValue('<?xml version="1.0" encoding="UTF-8"?>\n<usuarios>\n    <usuario id="1">\n        <nombre>Ana</nombre>\n    </usuario>\n</usuarios>');ta.focus();};host.querySelector('#xml-import').onclick=()=>T.readFile('.xml,application/xml,text/xml',txt=>{editor.setValue(txt);ta.focus();});host.querySelector('#xml-copy').onclick=e=>T.copy(ta.value,e.currentTarget);host.querySelector('#xml-download').onclick=()=>T.download('documento.xml',ta.value,'application/xml');host.querySelector('#xml-clear').onclick=()=>{editor.setValue('');};editor.validate();
}
T.views=T.views||{};T.views.xml=render;
})();
